### ISSUE TITLE
failed to create symbolic link '/opt/stremio/node': File exists error after qt5 update

### ISSUE THREAD

**Issue by emrahyumuk** [alexandru-balan/Stremio-Install-Scripts#10]
installStremioFedora.sh script throws 'failed to create symbolic link '/opt/stremio/node': File exists Can't install the project. MAKE error !' on Fedora 32 after qt5 update

**Comment by alexandru-balan** [comment]
For Fedora please use the official version provided on the Stremio website. Use the .rpm package to install through the Software Center.

Or you can even try the flatpak version that's also available on the official website. 

This repo is headed to obsolescence.

**Comment by emrahyumuk** [comment]
I installed offical version of stremio on the the stremio website. there was no problem. but flatpack and rpm package throw this error after qt5 update
