### ISSUE TITLE
Installation error on Fedora 31

### ISSUE THREAD

**Issue by rrgaya-zz** [alexandru-balan/Stremio-Install-Scripts#5]
-----------------------------------------------
Compiling and Installing Stremio to your system
-----------------------------------------------
installStremioFedora.sh: linha 26: qmake-qt5: comando não encontrado
mkdir -p build
cd build && qmake-qt5 PREFIX="" ..
/bin/sh: qmake-qt5: comando não encontrado
make: *** [release.makefile:32: build/stremio] Error 127
which: no node in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
make -C build install
make[1]: Entering directory '/home/gaya/Documentos/Stremio-Install-Scripts/stremio-shell/build'
make[1]: *** No rule to make target 'install'.  Pare.
make[1]: Leaving directory '/home/gaya/Documentos/Stremio-Install-Scripts/stremio-shell/build'
make: *** [release.makefile:14: install] Error 2
xdg-desktop-menu: file '/opt/stremio/smartcode-stremio.desktop' does not exist
./dist-utils/common/postinstall: linha 7: cd: /opt/stremio/icons: Arquivo ou diretório inexistente

**Comment by alexandru-balan** [comment]
Hi thanks for the submitted issue. I will update the script later today. I feel like they changed the command from qmake-qt5 to simply qmake

**Comment by alexandru-balan** [comment]
@rrgaya I have investigated your issue but unfortunately I cannot replicate it. `qmake-qt5` is still the name for the `qmake` command on fedora 31. Can you please make sure that you have installed the package *qt5-qtbase-devel* ?

To install it you can run: `sudo dnf install qt5-qtbase-devel`

**Comment by rrgaya-zz** [comment]
Yes I have installed. The error is related to mpv-libs-devel


Installing Dependencies

Last metadata expiration check: 0:03:44 ago on Thu 14 Nov 2019 11:28:38 AM -03.
Package nodejs-1:12.10.0-1.fc31.x86_64 is already installed.
Package wget-1.20.3-2.fc31.x86_64 is already installed.
No match for argument: mpv-libs-devel
Package qt5-qtbase-devel-5.12.5-1.fc31.x86_64 is already installed.
Package gcc-9.2.1-1.fc31.x86_64 is already installed.
Package gcc-c++-9.2.1-1.fc31.x86_64 is already installed.
Package make-1:4.2.1-14.fc31.x86_64 is already installed.
Package glibc-devel-2.30-5.fc31.x86_64 is already installed.
Package kernel-headers-5.3.11-300.fc31.x86_64 is already installed.
Package binutils-2.32-24.fc31.x86_64 is already installed.
Error: Unable to find a match: mpv-libs-devel

**Comment by alexandru-balan** [comment]
Hi @rrgaya ,
The `mpv-libs-devel` are required to build Stremio. It looks like you are missing the rpmfussion free repository. Please take a look at how to install it here https://rpmfusion.org/Configuration. Just click on the link for the fedora 31 and try running the script again. Let me know if this helps

**Comment by rrgaya-zz** [comment]
Perfect! That worked. Tks

**Comment by alexandru-balan** [comment]
Glad I could help you and thanks for using my scripts
