### ISSUE TITLE
Can't install on Fedora 31

### ISSUE THREAD

**Issue by NikosChatzivangelis** [alexandru-balan/Stremio-Install-Scripts#6]
I tried to install stremio on Fedora 31 but it kept showing an error saying:
"Can't set the project up. QMAKE error !"

I installed all the dependencies and also the qt5 libs but still the same error

**Comment by alexandru-balan** [comment]
Hi @nikoshatzivag,
I have updated the script for fedora can you please clone the repo again and confirm if this is fixed?

**Comment by NikosChatzivangelis** [comment]
> Hi @nikoshatzivag,
> I have updated the script for fedora can you please clone the repo again and confirm if this is fixed?

YEAH thanks now works fine!!

**Comment by alexandru-balan** [comment]
Glad I could help you

**Comment by changemenemo** [comment]
problem again:
```
wget "https://s3-eu-west-1.amazonaws.com/stremio-artifacts/four/master/server.js" -qO server.js || rm server.js
mkdir -p "icons"
cd "icons" && printf 16,22,24,32,64,128 | xargs -I^ -d, sh -c 'rsvg-convert ../images/stremio.svg -w ^ -o smartcode-stremio_^.png && rsvg-convert ../images/stremio_tray_white.svg -w ^ -o smartcode-stremio-tray_^.png'
make -C build install
make[1]: Entering directory '/home/snol/Stremio-Install-Scripts/stremio-shell/build'
/usr/bin/qmake-qt5 -install qinstall /home/snol/Stremio-Install-Scripts/stremio-shell/smartcode-stremio.desktop /opt/stremio/smartcode-stremio.desktop
/usr/bin/qmake-qt5 -install qinstall -exe stremio /opt/stremio/stremio
strip /opt/stremio/stremio
make[1]: Leaving directory '/home/snol/Stremio-Install-Scripts/stremio-shell/build'

install -Dm 644 server.js "/opt/stremio/server.js"
install: cannot stat 'server.js': No such file or directory
make: *** [release.makefile:15: install] Error 1
Can't install the project. MAKE error !
```

**Comment by alexandru-balan** [comment]
Hi @boistordu maybe the `server.js` file was not downloaded from the stremio AWS instance. Have you tried to run the install script again and have been met with the same error?

**Comment by changemenemo** [comment]
same error again and again

**Comment by changemenemo** [comment]
wait give me a moment I'm going to look for a problem with dns

**Comment by changemenemo** [comment]
yeah it was the dns which was causing momentarerly a problem:) thanks for pointing that out:)

**Comment by alexandru-balan** [comment]
Ok @boistordu, so everything fine? If yes, I'll close the issue again
